// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJNzOxtKIKBFh79Fc96XSeJaKANdMtKVA',
    appId: '1:90728640098:web:3932d501cc5f610b852b3b',
    messagingSenderId: '90728640098',
    projectId: 'impacthackv3',
    authDomain: 'impacthackv3.firebaseapp.com',
    storageBucket: 'impacthackv3.appspot.com',
    measurementId: 'G-DMED8X5Y4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN5p3CReoUSV2NYVbOZIM1MnIEHqE8CQQ',
    appId: '1:90728640098:android:ca866d4c29be509f852b3b',
    messagingSenderId: '90728640098',
    projectId: 'impacthackv3',
    storageBucket: 'impacthackv3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4TUWeubVBr5QRri_3CyH9mWHQ6RQYjKw',
    appId: '1:90728640098:ios:13b656734bb94870852b3b',
    messagingSenderId: '90728640098',
    projectId: 'impacthackv3',
    storageBucket: 'impacthackv3.appspot.com',
    iosClientId: '90728640098-spjuhkhj5ot171rne9663tao6oqmib6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.impactHackV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4TUWeubVBr5QRri_3CyH9mWHQ6RQYjKw',
    appId: '1:90728640098:ios:b01092dea699f752852b3b',
    messagingSenderId: '90728640098',
    projectId: 'impacthackv3',
    storageBucket: 'impacthackv3.appspot.com',
    iosClientId: '90728640098-85321gm84dprbdnguce1npqba7fr6321.apps.googleusercontent.com',
    iosBundleId: 'com.example.impactHackV3.RunnerTests',
  );
}
